# Author:  Thomas Laurenson
# Email:   thomas@thomaslaurenson.com
# Website: https://www.thomaslaurenson.com
#
# Description:
# Docker compose for the gcd_docker project
#
# Copyright (c) 2022, Thomas Laurenson
# 
###############################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
version: '3'

services:
  python:
    build:
      context: python
      dockerfile: Dockerfile
    image: python:3.9-slim-bullseye
    container_name: gcd_python
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./python/app:/app
    networks:
      - backend
  mysql:
    image: mysql:8.0
    container_name: gcd_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./gcd_data:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
