version: '3'

services:

  mysql:
    image: gcd-mysql:${TGD_DUMP_DATE_CURR}
    container_name: gcd-mysql:${TGD_DUMP_DATE_CURR}
    build:
      context: .
      dockerfile: tgd/mysql/Dockerfile
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=tgd
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./data/volumes/tgd_mysql_${TGD_DUMP_DATE_CURR}:/var/lib/mysql
      - ./data/tgd/:/docker-entrypoint-initdb.d
    networks:
      - backend

  python:
    image: gcd-python:${TGD_DUMP_DATE_CURR}
    container_name: gcd-python:${TGD_DUMP_DATE_CURR}
    build:
      context: .
      dockerfile: tgd/python/Dockerfile
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=tgd
      - MYSQL_PORT=${MYSQL_PORT}
      - GCD_DUMP_DATE_LAST=${GCD_DUMP_DATE_LAST}
      - GCD_DUMP_DATE_CURR=${GCD_DUMP_DATE_CURR}
      - TGD_DUMP_DATE_CURR=${TGD_DUMP_DATE_CURR}
    volumes:
      - ./python:/python
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
